--- #YAML:1.0
name:               MARC-XML
version:            0.93
abstract:           ~
author:
    - Ed Summers <ehs@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MARC::Charset:  0.98
    MARC::Record:   2
    XML::SAX:       0.12
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
