# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MARC-XML
version:      0.81
version_from: lib/MARC/File/XML.pm
installdirs:  site
requires:
    MARC::Charset:                 0.91
    MARC::Record:                  1.36
    XML::SAX:                      0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
